# Generated by Django 3.1.7 on 2021-03-30 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedclasses', to='supplyusapi.classlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateduser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shopping_link', models.CharField(max_length=500)),
                ('imageURL', models.CharField(max_length=500)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyusapi.supplytype')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('is_active_type', models.BooleanField()),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyusapi.supplyitem')),
            ],
        ),
        migrations.CreateModel(
            name='ClassListSupplyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('class_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyusapi.classlist')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyusapi.packagetype')),
                ('supply_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyusapi.supplyitem')),
            ],
        ),
    ]
